deployment:
  vault:
    secretPath: /v1/edc
    timeout: 30
  include:
    postgres: false 

ingress:
  enabled: true
  apiPath: /api
  managementPath: /management
  protocolPath: /protocol
  publicPath: /public
  controlPath: /control

# it would be better to move those to vault in the future or use sops encryption
env:
  edcParticipantId: ""
  edcIdsId: ""

contractmanager:
  extension:
    enabled: true
  url: http://contract-dataprovider:8080/contract/v1

javadebug:
  enabled: false
  port: 5006

serviceAccount:
  name: simpl-edc-service-account